# Generated by Django 5.1.3 on 2024-11-28 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_feedback_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='feedback',
            table='accounts_feedback',
        ),
    ]
